d /run/vgt-gedefense 0750 gedefense gedefense -
d /run/vgt-gedefense-l7 0750 gedefense gedefense-l7 -
d /var/lib/vgt/gedefense 1770 root gedefense -
d /var/lib/vgt/gedefense/quarantine 0700 root gedefense -
d /var/lib/vgt/gedefense/quarantine/objects 0700 root gedefense -
