d /run/vgt-gedefense 0750 gedefense gedefense -
d /var/lib/vgt/gedefense 0710 gedefense gedefense -
d /var/lib/vgt/gedefense/quarantine 0700 root gedefense -
d /var/lib/vgt/gedefense/quarantine/objects 0700 root gedefense -
