# STATUS: DIAMANT VGT SUPREME
[Unit]
Requires=gedefense-astraeaos-provision.service
After=gedefense-astraeaos-provision.service

[Service]
TimeoutStartSec=15s
ExecStart=
ExecStart=/usr/lib/astraeaos/gedefense-core-launch
